version: '3.3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: tsed/test-artillery:latest
    ports:
      - "3000:3000"
      - "9229:9229"
    stdin_open: true  # -i
    tty: true         # -t

